# Generated by Django 3.0.6 on 2020-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo1',
            field=models.ImageField(blank=True, default='static/blog/IMG_20190427_212741.jpg', null=True, upload_to='blog/static/blog'),
        ),
    ]
