# Generated by Django 3.0.6 on 2020-05-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200520_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo1',
            field=models.ImageField(blank=True, default='blog/IMG_20190427_212741.jpg', null=True, upload_to='blog'),
        ),
    ]
