# Generated by Django 3.0.6 on 2020-05-26 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200526_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo1',
            field=models.ImageField(blank=True, default='blog/IMG_20190427_212741.jpg', null=True, upload_to='blog'),
        ),
    ]
