# Generated by Django 3.0.6 on 2020-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200526_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='xxx'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='xx', max_length=200),
        ),
    ]
