# Generated by Django 3.0.6 on 2020-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recette_title', models.CharField(max_length=200)),
                ('recette_ingredients', models.CharField(max_length=2000)),
                ('precette_body', models.CharField(max_length=20000)),
                ('recette_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
