# Generated by Django 3.0.6 on 2020-05-26 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='recette_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='precette_body',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='recette_date',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='recette_ingredients',
        ),
        migrations.AddField(
            model_name='recette',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(default='xx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='text',
            field=models.TextField(default='xx'),
            preserve_default=False,
        ),
    ]
